name: Update CREDITS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install gocredits
        run: go install github.com/Songmu/gocredits/cmd/gocredits@latest

      - name: Run gocredits
        run: gocredits -skip-missing . > CREDITS

      - name: Commit and push if changed
        run: |
          git diff --exit-code --quiet CREDITS || git add CREDITS
          git diff --exit-code --quiet CREDITS || git commit -m "chore: Update CREDITS"
          git diff --exit-code --quiet CREDITS || git push origin main
